version: '3'
services:
        #PHP
        api:
                build:
                        context: .
                        dockerfile: Dockerfile
                        image: php:7.4-cli
                        container_name: agenda_api
                        restart: unless-stopped
                        tty: true
                        environment:
                                SERVICE_NAME: agenda_api
                                SERVICE_TAGS: dev
                        working_dir: /var/www
                        networks:
                                agenda-network

        #Nginx
                        webserver:
                                image: nginx:alpine
                                container_name: nginx_webserver
                                restart: unless-stopped
                                tty: true
                                ports:
                                        - 80:80
                                        - 443:443
                                networks:
                                        - agenda-network

         #MySql
                
